Document testing of OAA with KS
OpenSCAP/oscap-anaconda-addon pull request #198
Opened 2022-03-24 15:21 UTC by jan-cerny

Add https://github.com/OpenSCAP/oscap-anaconda-addon/pull/191 and https://github.com/OpenSCAP/oscap-anaconda-addon/pull/193 to master branch.

2022-03-24 15:24 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/OpenSCAP/oscap-anaconda-addon/inspections/04e2a337-59a0-433a-9aa8-11c31b5a6eba) was created.

2022-04-06 07:17 UTC, jan-cerny commented
Hello everyone, to clarify, this PR is only a port of already merged PRs to the master branch.

2022-04-07 12:43 UTC, matejak requested changes
Thanks, that's also great! Please don't be shy about install URLs, as Fedora is public, and also replace the RHEL8 ks with a working Fedora ks.

2022-04-08 12:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/OpenSCAP/oscap-anaconda-addon/inspections/e9ebe2cc-cbfa-4127-ab4a-0411c99a227c) was created.

2022-04-08 12:15 UTC, jan-cerny commented
updated

2022-04-08 12:15 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/OpenSCAP/oscap-anaconda-addon/inspections/e9ebe2cc-cbfa-4127-ab4a-0411c99a227c) completed: **No new issues**

2022-04-12 14:38 UTC, matejak approved these changes

2022-04-12 14:39 UTC, merged