Refactor content fetching
OpenSCAP/oscap-anaconda-addon pull request #237
Opened 2023-03-06 16:03 UTC by jan-cerny

#### Description:
This PR contains a series of small refactoring of the code responsible for content fetching, with focus on the `org_fedora_oscap.content_discovery.ContentBringer` class.

The main change is that the code performing analysis of the content has been moved away from `ContentBringer` to a new class `ContentAnalyzer`.

Moreover, code manipulating the members of the `PolicyData` class has been moved away from `ContentBringer` to the `PolicyData` class.

The outcome is that now the `ContentBringer` contains only code performing the download of the content and `ContentAnalyzer` contains only code performing the analysis of the already fetched content. These 2 classes are independent.

For more details, please read commit messages of all commits.

#### Rationale:
This change prepares the code for further refactoring with the goal to consolidate content fetching functionality. The separation of content fetching and content analysis functionality will allow us to focus on each of these 2 stages separately, with lower mutual collisions, in future PRs.

#### Review Hints:

cd testing_files/
python3 -m http.server

./create_update_image.sh install_addon_from_repo

./reanaconda.py updates ~/work/git/oscap-anaconda-addon/update.img

2023-03-06 16:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/OpenSCAP/oscap-anaconda-addon/inspections/0859852e-d227-42f8-919c-73a0314a051d) was created.

2023-03-06 16:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/OpenSCAP/oscap-anaconda-addon/inspections/0859852e-d227-42f8-919c-73a0314a051d) completed: **13 updated code elements**

2023-03-09 13:06 UTC, matejak requested changes
Thank you for the PR, it does many changes totally right, while some I don't like, so let's talk about them.

Great:

- Streamlining of the code.
- Factoring the analyzer out of the bringer.

Controversial:

- PolicyData getting new abilities. I agree with the ability to "clear" itself, but the rest should be responsibility of a different class. PolicyData should remain a data structure, an interface that other classes understand and use. This data structure shouldn't know that a thing s.a. "system content" or "downloadable content" exist.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/content_discovery.py
> +        path = url.split("://")[1]
This will crash in some cases of invalid URLs s.a. `http://`. We had a BZ about this recently, and the code that extracts path in a robust way is already in the project, that could be extracted as well.
The code also assumes that destdir is a pathlib path, so adding an appropriate type hint may be a good idea.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/content_discovery.py
> +        return self._content_uri
I suggest renaming to `_valid_content_uri`, so the code that uses it knows that it is safe to make certain assumptions.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/content_discovery.py
> +        self.dest_file_name = self.CONTENT_DOWNLOAD_LOCATION / basename
Why not to keep the code in that private method, and call it only once in the constructor?

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/content_discovery.py
> +    def finish_content_fetch(self, fetching_thread_name, fingerprint, dest_filename,
This is tricky, the report callback is supposed to be a function that I can use to get information out of the depths of data processing to the user in a good form. It may not be used because of simple omission, not because it doesn't make sense to use it. IOW, the fix for this unused argument could be that it is put to a use.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/structures.py
> -        self.dry_run = False
This is interesting, almost suspicious. Note to self - needs further investigation.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/gui/spokes/oscap.py
> -        self.content_bringer.use_system_content()
I disagree here - the content spec data class shouldn't have the knowledge what "system content" even is, and even how to get it. The "bringer" class knows this, and, of course, hammers the information into the content spec aspect of the "policy data" dataclass. It is OK for the bringer to know the data format of the content spec, and the content spec just has to store the data, it doesn't have to fully understand them to the finest extent.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/structures.py
> +    def use_downloaded_content(self, content):
Ditto, the logic of obtaining content is independent from the description of the intent. The PolicyData should store data that have objective meaning, and a single line of its definition shouldn't need to be touched if we decide to use different algorithm for content download, or other implementation detail.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/gui/spokes/oscap.py
> +            self.content_bringer.finish_content_fetch(
Note for self: Probably the right thing to do now, but we need to change how it works.
Code should read like a prose, not like a cipher game, as it reads right now.

2023-03-09 13:06 UTC, matejak commented on org_fedora_oscap/service/installation.py
> +        if fetching_thread_name is not None:
Note to self: Probably the right thing to do now, but we need to change how it works.
Code should read like a prose, not like a cipher game, as it reads right now. It is very well visible here that a variable storing a name of a thread is seriously abused.

2023-03-10 08:18 UTC, jan-cerny commented on org_fedora_oscap/content_discovery.py
> +        path = url.split("://")[1]
Good point, but in later commits in this PR, the ` __get_dest_file_name` is further removed and the code using the URI is consolidated at a single place: the `content_uri` setter method, in which the sanity of the URI is checked and an exception is raised.

2023-03-10 08:27 UTC, jan-cerny commented on org_fedora_oscap/content_discovery.py
> +        self.dest_file_name = self.CONTENT_DOWNLOAD_LOCATION / basename
Because the basename is derived from URI of the content and the URI will change each time a new content will be requested to fetch.

2023-03-10 08:54 UTC, jan-cerny commented on org_fedora_oscap/content_discovery.py
> +    def finish_content_fetch(self, fetching_thread_name, fingerprint, dest_filename,
Do you have an idea what information it should return?

2023-03-10 08:55 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/OpenSCAP/oscap-anaconda-addon/inspections/bfedab30-a4fc-45e0-ab51-db087dd65349) was created.

2023-03-10 08:56 UTC, jan-cerny commented
I have moved the methods out from the `PolicyData` class and then I have renamed `_content_uri`.

2023-03-15 08:30 UTC, jan-cerny commented
@matejak ^

2023-03-15 09:35 UTC, matejak approved these changes

2023-03-15 09:35 UTC, matejak commented
LGTM, thanks!

2023-03-15 09:35 UTC, merged